// Autogenerated
package main

import (
	"io"
	"strconv"
	"time"
)

func WriteBody(writer io.Writer, model Model) (err error) {
	if err == nil {
		_, err = io.WriteString(writer, "<!--\n  Generated at: ")
	}
	if err == nil {
		_, err = io.WriteString(writer, time.Now().Format("Jan 2, 2006 at 3:04pm (MST)"))
	}
	if err == nil {
		_, err = io.WriteString(writer, "  \n-->\n\n<body>\n  <h1>")
	}
	if err == nil {
		_, err = io.WriteString(writer, model.Title)
	}
	if err == nil {
		_, err = io.WriteString(writer, "</h1>")
	}
	err = WriteMessages(writer, model.Messages)
	if err == nil {
		_, err = io.WriteString(writer, "\n  ")
	}
	for i := 0; i < 5; i++ {
		if err == nil {
			_, err = io.WriteString(writer, "\n  Hello ")
		}
		if err == nil {
			_, err = io.WriteString(writer, strconv.Itoa(i))
		}
	}
	if err == nil {
		_, err = io.WriteString(writer, "\n</body>\n")
	}
	return err
}

func WriteMessages(writer io.Writer, messages []string) (err error) {
	if len(messages) > 0 {
		if err == nil {
			_, err = io.WriteString(writer, "\n  <ul>")
		}
		for _, message := range messages {
			if err == nil {
				_, err = io.WriteString(writer, "\n    <li>")
			}
			if err == nil {
				_, err = io.WriteString(writer, message)
			}
			if err == nil {
				_, err = io.WriteString(writer, "</li>")
			}
		}
		if err == nil {
			_, err = io.WriteString(writer, "\n  </ul>")
		}
	} else {
		if err == nil {
			_, err = io.WriteString(writer, "\n  <p>No messages</p>\n")
		}
	}
	return err
}
